name: es_compression
description: Compression framework providing FFI implementations for Brotli, Lz4, Zstd (Zstandard) with ready-to-use prebuilt binaries for Win/Linux/Mac.
version: 2.0.15
homepage: https://www.instantiations.com
issue_tracker: https://github.com/instantiations/es_compression/issues
repository: https://github.com/instantiations/es_compression

environment:
  sdk: '>=3.2.0 <4.0.0'

executables:
  escompress: es_compress

dependencies:
  args: ^2.7.0
  ffi: ^2.1.4
  lz4_ffi: ^1.0.0-dev.2
  stack_trace: ^1.12.1
  stream_channel: ^2.1.4

dev_dependencies:
  benchmark_harness: ^2.4.0
  collection: ^1.19.1
  lints: ^6.0.0
  test: ^1.28.0
